package com.example.trading.risk

enum class RiskRejectionReason {
    INVALID_ENTRY_PRICE,
    INVALID_STOP_LOSS,
    INVALID_TAKE_PROFIT,
    STOP_LOSS_WRONG_SIDE,
    TAKE_PROFIT_WRONG_SIDE,
    POOR_RISK_REWARD,
    MAX_POSITIONS_EXCEEDED,
    SINGLE_POSITION_LOCK_ACTIVE,
    DAILY_LOSS_LIMIT_REACHED,
    COOLDOWN_ACTIVE,
    RISK_AMOUNT_EXCEEDED,
    SPREAD_TOO_HIGH,
    STALE_DATA,
    DATA_QUALITY_FAILED
}
